Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.mps.lambdas.ContactMeHandler
      CodeUri: /Users/manvendrasingh/Development/repo/mps-lambdas/contact-me
      Runtime: java11
      Architectures:
        - x86_64